### PR TITLE
Delete Functionality

### PR DESCRIPTION
**Pull request by Brewski-Dev**

### CODE REVIEW

**Comment by DrRuski** [comment]
@Fermain I am having issues with getting the delete button so that i can .addEventListener to it, ive done this before but i cant remember and ive looked through the past assignments and place the buttonlistener function into several places but i always get "null" back when i log it, ive also tried asyncing back and forth, if u got like a hint or something, that would be great.
I know that the btnlistener should come after its created but im still confused.

**Comment by DrRuski** [comment]
Nevermind i got it to work.....

**Comment by DrRuski** [comment]
@Fermain Got the button and the id to work properly and i think im on the cusp of finishing it up, having minor issues with getting the ID to stick to the specific button, if u have any hints/tips i would appreciate it =)

**Comment by Brewski-Dev** [comment]
@Fermain So i got an small issue now, overall the delete function works with the exception of that it targets all of the posts when i press on one posts button, and i am kinda confused so if u have time to look at it, it would be awsome.
Thanks in advance.

**Comment by Fermain** [comment]
I think the issue is that there are many #deletePostButton ids, you need to narrow it down. The best time to set this listener is when you create the template.

```js
container.querySelector("button.delete").addEventListener(() => {
  deletePost(postData.id)
})
```

**Comment by Brewski-Dev** [comment]
@Fermain 
bilde

**Pull request merged**
